SELECT
  customer.id AS customer_id,
  customer.descriptive_name AS account_name,
  customer.currency_code AS currency,
  campaign.id AS campaign_id,
  campaign.name AS campaign_name,
  campaign.status AS status,
  campaign.start_date AS start_date,
  campaign.end_date AS end_date,
  campaign.bidding_strategy_type AS bidding_strategy,
  campaign_budget.amount_micros AS budget_amount,
  campaign_budget.total_amount_micros AS total_budget,
  campaign_budget.type AS budget_type,
  campaign_budget.explicitly_shared AS is_shared_budget,
  campaign_budget.period AS budget_period,
  campaign.target_cpa.target_cpa_micros AS target_cpa,
  campaign.target_roas.target_roas AS target_roas,
  campaign.maximize_conversion_value.target_roas AS max_conv_target_roas,
  campaign.maximize_conversions.target_cpa_micros AS max_conv_target_cpa,
  campaign.selective_optimization.conversion_actions AS selective_optimization_conversion_actions,
  campaign.network_settings.target_content_network AS target_content_network,
  campaign.network_settings.target_google_search AS target_google_search,
  campaign.network_settings.target_partner_search_network AS target_partner_search_network,
  campaign.network_settings.target_search_network AS target_search_network,
  campaign.video_brand_safety_suitability AS inventory_type,
  campaign.shopping_setting.merchant_id AS gmcid,
  metrics.cost_micros AS cost,
  metrics.conversions AS conversions,
FROM campaign
WHERE campaign.advertising_channel_type = "VIDEO"
